### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by Djerry-h** [CampanulaBells/PREM-GAD#2]
Hello, it's an honor to read your article, but I have some questions. Did the model consider real-world data that contains anomalies (e.g., YelpChi) during the experiments? I wonder if any related experimental analysis has been done?

**Comment by CampanulaBells** [comment]
Hi, we haven't tested it on other datasets yet. You can have a try!

**Comment by Djerry-h** [comment]
Sure, Professor, I have another small question. In the document, it mentions the dataset attributes. What does that refer to? Because when I printed Flicker, I didn't find the 12,407-dimensional value mentioned in the dataset. Could you take a look at the image I provided?
![1717417797670](https://github.com/CampanulaBells/PREM-GAD/assets/53307793/e092f4f9-4a22-42f0-8c4f-9e976a424971)
![1717418020318](https://github.com/CampanulaBells/PREM-GAD/assets/53307793/f96725ec-82f5-47f5-bb22-c3904364498d)

**Comment by CampanulaBells** [comment]
Hi, attributes refer to feature dimension. The 7575 is the number of nodes. So basically it is a matrix of node's features.

**Comment by Djerry-h** [comment]
Thank you for your patient response！
&nbsp;


deom
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年6月4日(星期二) 上午7:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CampanulaBells/PREM-GAD] Datasets (Issue #2)














 
Hi, attributes refer to feature dimension. The 7575 is the number of nodes. So basically it is a matrix of node's features.
